Repository BornToBeRoot/NETworkManager, pull requests merged in 2024-11, with the labels that each got.

#2876 Fix: Ping monitor crash when dns not configured
  Source/NETworkManager.Models/Network/Ping.cs
  Source/NETworkManager.Utilities/DNSClient.cs
  Source/NETworkManager/MainWindow.xaml.cs
  Website/docs/changelog/next-release.md
Labels: :bug: bug, :white_check_mark: LGTM

#2877 Feature: Profile description and tooltip
  Source/NETworkManager.Localization/Resources/StaticStrings.Designer.cs
  Source/NETworkManager.Localization/Resources/StaticStrings.resx
  Source/NETworkManager.Localization/Resources/Strings.Designer.cs
  Source/NETworkManager.Localization/Resources/Strings.resx
  Source/NETworkManager.Profiles/GroupInfo.cs
  Source/NETworkManager.Profiles/ProfileInfo.cs
  Source/NETworkManager/ProfileDialogManager.cs
  Source/NETworkManager/ViewModels/GroupViewModel.cs
  Source/NETworkManager/ViewModels/ProfileViewModel.cs
  Source/NETworkManager/Views/AWSSessionManagerHostView.xaml
  Source/NETworkManager/Views/DNSLookupHostView.xaml
  Source/NETworkManager/Views/GroupDialog.xaml
  Source/NETworkManager/Views/IPGeolocationHostView.xaml
  Source/NETworkManager/Views/IPScannerHostView.xaml
  Source/NETworkManager/Views/NetworkInterfaceView.xaml
  Source/NETworkManager/Views/PingMonitorHostView.xaml
  Source/NETworkManager/Views/PortScannerHostView.xaml
  Source/NETworkManager/Views/PowerShellHostView.xaml
  Source/NETworkManager/Views/ProfileDialog.xaml
  Source/NETworkManager/Views/PuTTYHostView.xaml
  Source/NETworkManager/Views/RemoteDesktopConnectDialog.xaml
  Source/NETworkManager/Views/RemoteDesktopHostView.xaml
  Source/NETworkManager/Views/SNMPHostView.xaml
  Source/NETworkManager/Views/TigerVNCHostView.xaml
  Source/NETworkManager/Views/TracerouteHostView.xaml
  Source/NETworkManager/Views/WakeOnLANView.xaml
  Source/NETworkManager/Views/WebConsoleHostView.xaml
  Source/NETworkManager/Views/WhoisHostView.xaml
  Website/docs/changelog/next-release.md
Labels: :rocket: feature-request, :white_check_mark: LGTM

#2846 Fix: Refactor network connection & other dashboards
  Source/NETworkManager.Models/Generated Files/CsWinRT/WinRTEventHelpers.cs
  Source/NETworkManager.Settings/GlobalStaticConfiguration.cs
  Source/NETworkManager.Utilities/DNSClient.cs
  Source/NETworkManager/App.xaml.cs
  Source/NETworkManager/Generated Files/CsWinRT/WinRTEventHelpers.cs
  Source/NETworkManager/MainWindow.xaml
  Source/NETworkManager/MainWindow.xaml.cs
  Source/NETworkManager/StatusWindow.xaml.cs
  Source/NETworkManager/ViewModels/DashboardViewModel.cs
  Source/NETworkManager/ViewModels/IPApiDNSResolverWidgetViewModel.cs
  Source/NETworkManager/ViewModels/IPApiIPGeolocationWidgetViewModel.cs
  Source/NETworkManager/ViewModels/NetworkConnectionWidgetViewModel.cs
  Source/NETworkManager/ViewModels/WiFiViewModel.cs
  Source/NETworkManager/Views/DashboardView.xaml.cs
  Source/NETworkManager/Views/IPApiDNSResolverWidgetView.xaml
  Source/NETworkManager/Views/IPApiDNSResolverWidgetView.xaml.cs
  Source/NETworkManager/Views/IPApiIPGeolocationWidgetView.xaml
  Source/NETworkManager/Views/IPApiIPGeolocationWidgetView.xaml.cs
  Source/NETworkManager/Views/NetworkConnectionWidgetView.xaml
  Source/NETworkManager/Views/NetworkConnectionWidgetView.xaml.cs
Labels: :bug: bug, :hammer_and_wrench: code-cleanup, :white_check_mark: LGTM

#2910 Introducing NETworkManager Guru on Gurubase.io
  README.md
Labels: :book: documentation, :white_check_mark: LGTM

#2914 Fix: Change dialog to child window to allow drag & resize
  Source/GlobalAssemblyInfo.cs
  Source/NETworkManager/MainWindow.xaml
  Source/NETworkManager/MainWindow.xaml.cs
  Source/NETworkManager/NETworkManager.csproj
  Source/NETworkManager/Views/WelcomeChildWindow.xaml
  Source/NETworkManager/Views/WelcomeChildWindow.xaml.cs
  Website/docs/changelog/next-release.md
Labels: :bug: bug, :art: design, :white_check_mark: LGTM

#2912 Feature: Support WiFi 6 GHz & WPA3
  Source/NETworkManager.Controls/NETworkManager.Controls.csproj
  Source/NETworkManager.Converters/NETworkManager.Converters.csproj
  Source/NETworkManager.Documentation/NETworkManager.Documentation.csproj
  Source/NETworkManager.Localization/NETworkManager.Localization.csproj
  Source/NETworkManager.Models/NETworkManager.Models.csproj
  Source/NETworkManager.Models/Network/WiFi.cs
  Source/NETworkManager.Models/Network/WiFiNetworkInfo.cs
  Source/NETworkManager.Models/Network/WiFiRadio.cs
  Source/NETworkManager.Profiles/NETworkManager.Profiles.csproj
  Source/NETworkManager.Settings/NETworkManager.Settings.csproj
  Source/NETworkManager.Update/NETworkManager.Update.csproj
  Source/NETworkManager.Utilities.WPF/NETworkManager.Utilities.WPF.csproj
  Source/NETworkManager.Utilities/NETworkManager.Utilities.csproj
  Source/NETworkManager.Validators/NETworkManager.Validators.csproj
  Source/NETworkManager/NETworkManager.csproj
  Source/NETworkManager/ViewModels/WiFiViewModel.cs
  Source/NETworkManager/Views/WiFiView.xaml
  Website/docs/application/wifi.md
  Website/docs/changelog/next-release.md
Labels: :bug: bug, :rocket: feature-request, :book: documentation, :white_check_mark: LGTM

#2928 Feature: Filter 6 GHz network / refactor code
  Source/NETworkManager.Converters/WiFiChannelCenterFrequencyToChannelStringConverter.cs
  Source/NETworkManager.Converters/WiFiChannelCenterFrequencyToFrequencyStringConverter.cs
  Source/NETworkManager.Localization/Resources/Strings.Designer.cs
  Source/NETworkManager.Localization/Resources/Strings.resx
  Source/NETworkManager.Models/Network/WiFi.cs
  Source/NETworkManager.Models/Network/WiFiNetworkInfo.cs
  Source/NETworkManager.Models/Network/WiFiRadio.cs
  Source/NETworkManager.Settings/GlobalStaticConfiguration.cs
  Source/NETworkManager.Settings/SettingsInfo.cs
  Source/NETworkManager/ViewModels/WiFiViewModel.cs
  Source/NETworkManager/Views/WiFiView.xaml
  Website/docs/application/wifi.md
  Website/docs/changelog/next-release.md
Labels: :rocket: feature-request, :hammer_and_wrench: code-cleanup, :white_check_mark: LGTM

#2940 Feature: WiFi - Improve search / remove converters
  Source/NETworkManager.Converters/WiFiAuthenticationTypeToHumanReadableStringConverter.cs
  Source/NETworkManager.Converters/WiFiChannelCenterFrequencyToChannelStringConverter.cs
  Source/NETworkManager.Converters/WiFiPhyKindToStringConverter.cs
  Source/NETworkManager.Models/Network/WiFi.cs
  Source/NETworkManager.Models/Network/WiFiNetworkInfo.cs
  Source/NETworkManager/ViewModels/WiFiViewModel.cs
  Source/NETworkManager/Views/WiFiView.xaml
  Website/docs/application/wifi.md
  Website/docs/changelog/next-release.md
Labels: :rocket: feature-request, :book: documentation, :hammer_and_wrench: code-cleanup, :white_check_mark: LGTM
